-- MySQL Script generated by MySQL Workbench
-- Tue Dec 12 16:34:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mobile_shop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mobile_shop` ;

-- -----------------------------------------------------
-- Schema mobile_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mobile_shop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mobile_shop` ;

-- -----------------------------------------------------
-- Table `mobile_shop`.`customer_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobile_shop`.`customer_category` ;

CREATE TABLE IF NOT EXISTS `mobile_shop`.`customer_category` (
  `id` VARCHAR(7) NOT NULL,
  `name` VARCHAR(1000) NOT NULL,
  `discount` DOUBLE NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mobile_shop`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobile_shop`.`customer` ;

CREATE TABLE IF NOT EXISTS `mobile_shop`.`customer` (
  `id` VARCHAR(7) NOT NULL,
  `name` VARCHAR(1000) NOT NULL,
  `address` VARCHAR(1000) NULL DEFAULT NULL,
  `gender` TINYINT(1) NOT NULL,
  `birthday` DATETIME NULL DEFAULT NULL,
  `phone` VARCHAR(10) NULL DEFAULT NULL,
  `id_category` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_category` (`id_category` ASC) VISIBLE,
  CONSTRAINT `customer_ibfk_1`
    FOREIGN KEY (`id_category`)
    REFERENCES `mobile_shop`.`customer_category` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mobile_shop`.`work_shift`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobile_shop`.`work_shift` ;

CREATE TABLE IF NOT EXISTS `mobile_shop`.`work_shift` (
  `id` VARCHAR(7) NOT NULL,
  `name` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mobile_shop`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobile_shop`.`staff` ;

CREATE TABLE IF NOT EXISTS `mobile_shop`.`staff` (
  `id` VARCHAR(7) NOT NULL,
  `name` VARCHAR(1000) NOT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  `address` VARCHAR(1000) NULL DEFAULT NULL,
  `gender` TINYINT(1) NOT NULL,
  `birthday` DATETIME NULL DEFAULT NULL,
  `phone` VARCHAR(10) NULL DEFAULT NULL,
  `role` TINYINT(1) NOT NULL,
  `id_shift` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_shift` (`id_shift` ASC) VISIBLE,
  CONSTRAINT `staff_ibfk_1`
    FOREIGN KEY (`id_shift`)
    REFERENCES `mobile_shop`.`work_shift` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mobile_shop`.`bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobile_shop`.`bill` ;

CREATE TABLE IF NOT EXISTS `mobile_shop`.`bill` (
  `id` VARCHAR(7) NOT NULL,
  `date` DATETIME NOT NULL,
  `status` VARCHAR(1000) NULL DEFAULT NULL,
  `id_customer` VARCHAR(7) NOT NULL,
  `id_staff` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_customer` (`id_customer` ASC) VISIBLE,
  INDEX `id_staff` (`id_staff` ASC) VISIBLE,
  CONSTRAINT `bill_ibfk_1`
    FOREIGN KEY (`id_customer`)
    REFERENCES `mobile_shop`.`customer` (`id`),
  CONSTRAINT `bill_ibfk_2`
    FOREIGN KEY (`id_staff`)
    REFERENCES `mobile_shop`.`staff` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mobile_shop`.`object_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobile_shop`.`object_category` ;

CREATE TABLE IF NOT EXISTS `mobile_shop`.`object_category` (
  `id` VARCHAR(7) NOT NULL,
  `name` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mobile_shop`.`object`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobile_shop`.`object` ;

CREATE TABLE IF NOT EXISTS `mobile_shop`.`object` (
  `id` VARCHAR(7) NOT NULL,
  `name` VARCHAR(1000) NOT NULL,
  `status` VARCHAR(1000) NOT NULL,
  `manufacture` VARCHAR(1000) NOT NULL,
  `unitprice` INT NULL DEFAULT NULL,
  `id_category` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_category` (`id_category` ASC) VISIBLE,
  CONSTRAINT `object_ibfk_1`
    FOREIGN KEY (`id_category`)
    REFERENCES `mobile_shop`.`object_category` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mobile_shop`.`bill_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobile_shop`.`bill_detail` ;

CREATE TABLE IF NOT EXISTS `mobile_shop`.`bill_detail` (
  `count` INT NOT NULL,
  `id_object` VARCHAR(7) NOT NULL,
  `id_bill` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`id_object`, `id_bill`),
  INDEX `id_bill` (`id_bill` ASC) VISIBLE,
  CONSTRAINT `bill_detail_ibfk_1`
    FOREIGN KEY (`id_object`)
    REFERENCES `mobile_shop`.`object` (`id`),
  CONSTRAINT `bill_detail_ibfk_2`
    FOREIGN KEY (`id_bill`)
    REFERENCES `mobile_shop`.`bill` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mobile_shop`.`suplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobile_shop`.`suplier` ;

CREATE TABLE IF NOT EXISTS `mobile_shop`.`suplier` (
  `id` VARCHAR(7) NOT NULL,
  `name` VARCHAR(1000) NOT NULL,
  `address` VARCHAR(1000) NOT NULL,
  `phone` VARCHAR(10) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mobile_shop`.`receipt_note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobile_shop`.`receipt_note` ;

CREATE TABLE IF NOT EXISTS `mobile_shop`.`receipt_note` (
  `id` VARCHAR(7) NOT NULL,
  `date` DATETIME NOT NULL,
  `more_info` VARCHAR(1000) NULL DEFAULT NULL,
  `id_suplier` VARCHAR(7) NOT NULL,
  `id_staff` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_suplier` (`id_suplier` ASC) VISIBLE,
  INDEX `id_staff` (`id_staff` ASC) VISIBLE,
  CONSTRAINT `receipt_note_ibfk_1`
    FOREIGN KEY (`id_suplier`)
    REFERENCES `mobile_shop`.`suplier` (`id`),
  CONSTRAINT `receipt_note_ibfk_2`
    FOREIGN KEY (`id_staff`)
    REFERENCES `mobile_shop`.`staff` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mobile_shop`.`rn_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mobile_shop`.`rn_detail` ;

CREATE TABLE IF NOT EXISTS `mobile_shop`.`rn_detail` (
  `unit_price` INT NOT NULL,
  `count` INT NOT NULL,
  `id_receipt` VARCHAR(7) NOT NULL,
  `id_object` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`id_receipt`, `id_object`),
  INDEX `id_object` (`id_object` ASC) VISIBLE,
  CONSTRAINT `rn_detail_ibfk_1`
    FOREIGN KEY (`id_receipt`)
    REFERENCES `mobile_shop`.`receipt_note` (`id`),
  CONSTRAINT `rn_detail_ibfk_2`
    FOREIGN KEY (`id_object`)
    REFERENCES `mobile_shop`.`object` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
